#!/bin/bash
cordova platform remove android \
&& cordova platform remove browser \
&& cordova plugin add cordova-plugin-device \
&& cordova plugin add phonegap-nfc-api31 \
&& cordova plugin add cordova-plugin-networkinterface \
&& cordova plugin add cordova-plugin-file \
&& cordova plugin add cordova-plugin-android-permissions \
&& cordova plugin add cordova-plugin-app-version \
&& cordova plugin add cordova-plugin-bluetooth-serial \
&& cordova platform add android@12.0.1 \
&& cordova build android
